#
# Module manifest for module 'Reset-KrbTgtPassword'
#
# Generated by: Jorge de Almeida Pinto [MVP-EMS]
#
# Generated on: 2025-10-21
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Reset-KrbTgtPassword.psm1'

# Version number of this module.
ModuleVersion = '4.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '7c8a5e67-9f34-4d2b-8b6a-1e3d4f5c6b7a'

# Author of this module
Author = 'Jorge de Almeida Pinto [MVP-EMS]'

# Company or vendor of this module
CompanyName = 'IAMTEC >> Identity | Security | Recovery'

# Copyright statement for this module
Copyright = '(c) 2023-2025 Jorge de Almeida Pinto. All rights reserved. GPL License.'

# Description of the functionality provided by this module
Description = 'PowerShell module for resetting KrbTgt account passwords for RWDCs and RODCs in Active Directory environments. Includes simulation, testing, and production reset capabilities with comprehensive replication monitoring.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# GroupPolicy module is required for full functionality but not for module loading
# RequiredModules = @('GroupPolicy')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Reset-KrbTgtPassword',
    'New-TestKrbTgtAccount',
    'Remove-TestKrbTgtAccount',
    'Get-KrbTgtInfo',
    'Test-ADReplication',
    'Invoke-KrbTgtPasswordReset'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('ActiveDirectory', 'Security', 'KrbTgt', 'Kerberos', 'RODC', 'RWDC', 'Password', 'Reset')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/zjorz/Public-AD-Scripts/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/zjorz/Public-AD-Scripts'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
v4.0.0, 2025-10-21:
- Major restructuring: Converted monolithic script to modular PowerShell module
- New modular architecture with separate Public and Private functions
- Maintained all original functionality across 9 operation modes
- Improved testability and maintainability
- Better code organization and reusability
- Preserved backward compatibility with original script parameters
- Enhanced documentation and help system
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
